version: "3.4"
services:
  postgres:
    image: "postgres:15"
    container_name: "testpostgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=plumber_db
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: